//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggingServer.NotificationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotificationService.INotifyService")]
    public interface INotifyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifyService/Foo", ReplyAction="http://tempuri.org/INotifyService/FooResponse")]
        void Foo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifyService/Foo", ReplyAction="http://tempuri.org/INotifyService/FooResponse")]
        System.Threading.Tasks.Task FooAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotifyServiceChannel : LoggingServer.NotificationService.INotifyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotifyServiceClient : System.ServiceModel.ClientBase<LoggingServer.NotificationService.INotifyService>, LoggingServer.NotificationService.INotifyService {
        
        public NotifyServiceClient() {
        }
        
        public NotifyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotifyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotifyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotifyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Foo() {
            base.Channel.Foo();
        }
        
        public System.Threading.Tasks.Task FooAsync() {
            return base.Channel.FooAsync();
        }
    }
}
